{% set name = "jsonalias" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e397874a4a13b45c500565703dc71bd42011efde0570246de7a92d284610ac4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - jsonalias
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  # downstreams:
  #  - solders

about:
  home: https://github.com/kevinheavey/jsonalias
  summary: 'A microlibrary that defines a Json type alias for Python.'
  description: |
    A microlibrary that defines a Json type alias for Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
